sudo: false
dist: trusty
language: ruby
cache: bundler
addons:
    apt:
        - pandoc
        - hunspell
        - libhunspell-dev
        - hunspell-en-us
rvm:
    - 2.2
branches:
    only:
        develop
before_install:
    - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
    - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
    - git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials 2>/dev/null
    - git config --global user.email "${COMMITTER_EMAIL}"
    - git config --global user.name "${AUTHOR_NAME}"
    - git config --global submodule.recurse true
    - git config --global submodule.fetchJobs 8
    - pip install -r requirements.txt
before_script:
    - $TRAVIS_BUILD_DIR/_scripts/before_script.sh
after_success:
    - $TRAVIS_BUILD_DIR/_scripts/after_success.sh
    - $TRAVIS_BUILD_DIR/_scripts/check_markdown.sh
deploy:
    local_dir: _site
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN 
    target_branch: master
    depth: 1
    fqdn: cs241.cs.illinois.edu
    on:
        branch: develop
