sudo: false
dist: xenial
language: ruby
cache:
    bundler: true
    pip: true
addons:
    apt:
        packages:
            - pandoc
            - hunspell
            - libhunspell-dev
            - hunspell-en-us
            - python3-setuptools
            - python3-pip
rvm:
    - 2.5.3
branches:
    only:
        develop
before_install:
    - python3 -m pip install -U pip
    - python3 -m pip install --user -r requirements.txt
    - bash _scripts/check_markdown.sh
    - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
    - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
    - git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials 2>/dev/null
    - git config --global user.email "${COMMITTER_EMAIL}"
    - git config --global user.name "${AUTHOR_NAME}"
    - git config --global submodule.recurse true
    - git config --global submodule.fetchJobs 8
before_script:
    - echo Dummy Step
after_success:
    - $TRAVIS_BUILD_DIR/_scripts/after_success.sh
deploy:
    local_dir: _site
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN 
    target_branch: master
    depth: 1
    fqdn: cs241.cs.illinois.edu
    on:
        branch: develop
