# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "CS 241: System Programming"
email: angrave@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  Webpage for CS 241: System Programming at the University of Illinois Urbana-Champaign.
  All documentation and information about the course can be found here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://illinois-cs241.github.io" # the base hostname & protocol for your site
repository: illinois-cs241/illinois-cs241.github.io
docs_repository: illinois-cs241/assignment-docs
github_username: illinois-cs241
# Settings for the course
# semester is generated automagically
course_number: "241"
subject_code: "cs"
course_name: "System Programming"
exclude: [.git, README.md, deploy_rsa.enc, vendor, bundle]
navbar_items:
  - name: "Assignments"
    link: "assignments"
  - name: "Quizzes"
    link: "quiz_topics"
  - name: "Help!"
    link: "help"
  - name: "Schedule"
    link: "schedule"
  - name: "Honors"
    link: "honors"
  - name: "The Crew"
    link: "staff"
  - name: "Search"
    link: "search"
  - name: "Wikibook"
    link: "wikibook/home"
plugins_dir: _plugins
# Settings for docs collection
collections:
  docs:
    output: true
    permalink: /:path
  pages:
    output: true
    permalink: /:path
  resources:
    output: true
    permalink: /resources/:path
  wikibook:
    output: true
    permalink: /wikibook/:path
  tutorials:
    output: true
    permalink: /:path
# Build settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge
plugins:
  - jemoji
  - jekyll-include-cache
